### ISSUE TITLE
MQTT Mode?

### ISSUE THREAD

**Issue by Pacers31Colts18** [sparky8512/starlink-grpc-tools#54]
Having trouble getting this to work with MQTT. Am able to run, but when I try to use the MQTT script, I'm running into issues with the mode option, assuming I'm not doing something right.

Here is what I have

python3 dish_grpc_mqtt.py --hostname xxxxxx --port 1883 --username mqtt-user --password xxxxxxxxx mode usage

I've tried different variations, with 'usage' mode=usage --mode, etc, etc. Any thougts?

**Comment by sparky8512** [comment]
The mode argument is positional, so you don't actually include the word 'mode' on the command line, you just list the data group modes you want to emit:
```shell
python3 dish_grpc_mqtt.py --hostname xxxxxx --port 1883 --username mqtt-user --password xxxxxxxxx usage
```

There has to be at least one, though, which is why the usage line in the help output has the first 'mode' outside the braces. That's just how the `argparse` library depicts things.

**Comment by sparky8512** [comment]
I'm going to assume this has addressed the problem you were having and close this issue out. If not, feel free to reopen and attach full error output.
