### ISSUE TITLE
Obstruction map - which way is "up" ? 

### ISSUE THREAD

**Issue by iam-TJ** [sparky8512/starlink-grpc-tools#85]
Late to the party but wondering how to map compass directions to the PNG ?

I'm tending to think the lower edge of the PNG is South?
![obstructions-2](https://github.com/sparky8512/starlink-grpc-tools/assets/1151442/2bae0454-d370-443e-8e3b-2db6621f4be9)

My dish has unobstructed 360 view but there is a tall structure to the north ("behind" the dish). Latitude is 54 degrees.

**Comment by sparky8512** [comment]
I guess I never did document that, probably because the protocol doesn't indicate what the individual map points mean beyond "rows" and "columns". The way the mobile app display that map data makes it pretty apparent, though.

The exact technical description is a little involved due to coordinate system being converted into Cartesian coordinates, but if you only care about azimuth (compass direction), that's simple enough: The center top of the image is North, top right corner is Northeast, etc.

Altitude (elevation) angle is a little more complicated. The center of the image is "up" (zenith), and it gets closer to the horizon the further away from the center point it is. Note that this is center of the image, not center of the blob of white pixels, and "up" is from the perspective of an observer located at the dish, not the direction the dish is pointing.

**Comment by sparky8512** [comment]
There is now a more technical description of direction to pixel coordinate mapping documented at the top of the `dish_obstruction_map.py` script. 

If there are no further questions, let's close out this issue.
